on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '**'
name: Test
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        go-version: [1.16.x, 1.17.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        stable: false
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Test
      run: |
        go test ./...
        go test -race ./...

    - name: Tidy
      if: matrix.os == 'ubuntu-latest' # no need to do this everywhere
      run: |
        go mod tidy

        test -z "$(gofmt -d .)" || (gofmt -d . && false)
        test -z "$(git status --porcelain)" || (git status; git diff && false)

  test-gotip:
    runs-on: ubuntu-latest
    continue-on-error: true # master breaks sometimes
    steps:
    - name: Install Go
      env:
        GO_COMMIT: d0dd26a88c019d54f22463daae81e785f5867565 # 2021-09-23
      run: |
        cd $HOME
        mkdir $HOME/gotip
        cd $HOME/gotip

        wget -O gotip.tar.gz https://go.googlesource.com/go/+archive/${GO_COMMIT}.tar.gz
        tar -xf gotip.tar.gz
        echo "devel go1.18-${GO_COMMIT}" >VERSION

        cd src
        ./make.bash
        echo "GOROOT=$HOME/gotip" >>$GITHUB_ENV
        echo "$HOME/gotip/bin" >>$GITHUB_PATH
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Test
      run: |
        go version
        go test ./...
